[package]
name = "cybflight-msgs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
defmt = "1.0.1"
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
nalgebra = { version = "0.34.1", default-features = false, features = ["libm", "defmt"] }
