use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Copy memory.x to OUT_DIR so it overrides embassy-stm32's generated linker script.
    // This shrinks the FLASH region from 2048K to 1920K, reserving sector 7 for params.
    let out = std::env::var("OUT_DIR").unwrap();
    fs::copy("memory.x", Path::new(&out).join("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out);

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    println!("cargo:rerun-if-changed=memory.x");

    bake_thrust_tables(&PathBuf::from(&out));
}

/// Parse every CSV under `data/thrust_tables/` and emit `$OUT_DIR/thrust_tables.rs`.
///
/// CSV format (matches `tmp/thrust_map/code/thrust_map.cpp`):
///   line 1: `map_size, thrust_min, thrust_max, voltage_min, voltage_max, ...`
///           (extra trailing zeros padded to map_size columns are ignored)
///   lines 2..1+map_size: each row is `map_size` comma-separated f32 values,
///           indexed `grid[row=i_voltage][col=i_thrust]`.
///
/// **Thrust convention.** The bench rig measures *collective* thrust of all
/// `N_MOTORS` rotors running at the same command. INDI's linearization works
/// in *single-rotor* units (`u * per_motor_max_n` is one motor's force in N).
/// To match conventions, we divide the header `thrust_min` / `thrust_max` by
/// `N_MOTORS` before constructing the `ThrustTable`. The grid values are
/// commands and stay unchanged: one motor running at command `c` produces
/// `1/N_MOTORS` of the collective force the rig saw at that command.
/// Assumes all motors are identical (same param/dynamics) — fine for a
/// symmetric quad; revisit this for asymmetric airframes.
///
/// Build-time validation:
///   * `map_size == 50` (must match `cybflight_core::indi::linearization::TABLE_N`);
///   * thrust/voltage ranges are finite + monotone increasing;
///   * every grid cell parses as f32 and is finite;
///   * grid is non-decreasing along the thrust axis (row-wise) — this is the
///     monotonicity assumption that `ThrustTable::invert` relies on.
///
/// Build fails if any check fails. The MCU never parses CSV at runtime.
fn bake_thrust_tables(out: &Path) {
    const N: usize = 50; // matches TABLE_N in cybflight_core::indi::linearization
    // Matches `cybflight_core::indi::controller::NU`. Kept as a local const
    // because build.rs can't depend on the runtime crate; bump both together
    // if the actuator count ever changes.
    const N_MOTORS: usize = 4;

    let dir = Path::new("data/thrust_tables");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut emitted = String::new();
    emitted.push_str("// Auto-generated by build.rs from data/thrust_tables/*.csv.\n");
    emitted.push_str("// Do not edit by hand.\n\n");

    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => {
            // No data dir → emit an empty module. Firmware that doesn't need
            // a baked table builds fine.
            fs::write(out.join("thrust_tables.rs"), &emitted).unwrap();
            return;
        }
    };

    for entry in entries {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("csv") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        let const_name = stem
            .to_uppercase()
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
            .collect::<String>();

        let raw = fs::read_to_string(&path).expect("read thrust map csv");
        let mut lines = raw.lines().filter(|l| !l.trim().is_empty());

        // Header.
        let header = lines.next().expect("thrust map: missing header");
        let mut hdr = header.split(',').map(|s| s.trim());
        let map_size: usize = hdr
            .next()
            .expect("thrust map: missing map_size")
            .parse::<f64>()
            .expect("thrust map: map_size not a number") as usize;
        let thrust_min: f64 = hdr.next().expect("missing thrust_min").parse().unwrap();
        let thrust_max: f64 = hdr.next().expect("missing thrust_max").parse().unwrap();
        let voltage_min: f64 = hdr.next().expect("missing voltage_min").parse().unwrap();
        let voltage_max: f64 = hdr.next().expect("missing voltage_max").parse().unwrap();

        assert_eq!(
            map_size, N,
            "thrust map {}: expected {N}×{N} grid, got {map_size}",
            path.display()
        );
        assert!(thrust_max > thrust_min, "thrust map {}: thrust range degenerate", path.display());
        assert!(voltage_max > voltage_min, "thrust map {}: voltage range degenerate", path.display());

        // Collective → per-rotor conversion. See module doc on `bake_thrust_tables`.
        let thrust_min = thrust_min / N_MOTORS as f64;
        let thrust_max = thrust_max / N_MOTORS as f64;

        // Rows.
        let mut grid = [[0.0_f32; N]; N];
        for (row, row_buf) in grid.iter_mut().enumerate() {
            let line = lines
                .next()
                .unwrap_or_else(|| panic!("thrust map {}: row {row} missing", path.display()));
            let cols: Vec<&str> = line.split(',').take(N).collect();
            assert_eq!(
                cols.len(),
                N,
                "thrust map {}: row {row} has {} cols, expected {N}",
                path.display(),
                cols.len()
            );
            let mut prev = f32::NEG_INFINITY;
            for (col, s) in cols.iter().enumerate() {
                let v: f32 = s
                    .trim()
                    .parse()
                    .unwrap_or_else(|_| panic!("thrust map {}: row {row} col {col} not f32: {s:?}", path.display()));
                assert!(v.is_finite(), "thrust map {}: row {row} col {col} not finite", path.display());
                assert!(
                    v >= prev - 1e-3,
                    "thrust map {}: row {row} not monotone in thrust at col {col}: {prev} → {v}",
                    path.display()
                );
                prev = v;
                row_buf[col] = v;
            }
        }

        // Emit the static.
        emitted.push_str(&format!("/// Baked from `data/thrust_tables/{stem}.csv` at build time.\n"));
        emitted.push_str(&format!(
            "pub static {const_name}: ::cybflight_core::indi::thrust_table::ThrustTable<{N}> = match \
             ::cybflight_core::indi::thrust_table::ThrustTable::<{N}>::new(\n    [\n"
        ));
        for row in &grid {
            emitted.push_str("        [");
            for (j, v) in row.iter().enumerate() {
                if j > 0 {
                    emitted.push_str(", ");
                }
                emitted.push_str(&format!("{:e}_f32", v));
            }
            emitted.push_str("],\n");
        }
        emitted.push_str("    ],\n");
        emitted.push_str(&format!("    {thrust_min}_f32,\n"));
        emitted.push_str(&format!("    {thrust_max}_f32,\n"));
        emitted.push_str(&format!("    {voltage_min}_f32,\n"));
        emitted.push_str(&format!("    {voltage_max}_f32,\n"));
        emitted.push_str(") {\n    Some(t) => t,\n    None => panic!(\"baked thrust table failed validation\"),\n};\n\n");
    }

    fs::write(out.join("thrust_tables.rs"), emitted).expect("write thrust_tables.rs");
}
