use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Copy memory.x to OUT_DIR so it overrides embassy-stm32's generated linker script.
    // This shrinks the FLASH region from 2048K to 1792K, reserving bank-2
    // sectors 6+7 (the last 256K) for the parameter key-value store.
    let out = std::env::var("OUT_DIR").unwrap();
    fs::copy("memory.x", Path::new(&out).join("memory.x")).unwrap();
    println!("cargo:rustc-link-search={}", out);

    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    println!("cargo:rerun-if-changed=memory.x");

    let tables = bake_thrust_tables(&PathBuf::from(&out));
    let missions = bake_missions(&PathBuf::from(&out));
    vehicle_bake::run(&PathBuf::from(&out), &tables, &missions);
}

/// Parse every mission YAML under `missions/` (workspace root), validate
/// via the shared `vehicle_yaml::mission` loader, and emit
/// `$OUT_DIR/missions.rs` — the `PROFILES` table `include!`d by
/// `control/offline_mission.rs`. Adding a mission = dropping the offline
/// planner's output file in `missions/`; the loader performs the
/// conversions that used to be done by hand (durations → timestamps,
/// duplicate-head drop) and a malformed file fails the BUILD, not the
/// flight.
///
/// Emitted items (all in `offline_mission`'s scope):
/// - one waypoint/timestamp static pair + `MissionProfile` per file,
///   `PROFILES` sorted by file stem (= mission name; NOTE: persisted
///   `mission_profile` indices refer to this order — re-run `mission set`
///   after adding/removing mission files);
/// - `OFFLINE_MAX_PIECES` = the actual max piece count (bounded by
///   `cybflight_core::trajectory_planning::MAX_PIECES`), so the
///   mission-planner scratch arrays auto-size to the data;
/// - `DEFAULT_PROFILE_INDEX_{INDOOR,OUTDOOR}`: `*_splits_slow` when
///   present (the historical defaults), else the first mission of that
///   env, else 0.
///
/// Returns the sorted `(name, env)` list so the vehicle bake can resolve
/// the YAML `default_mission` name to an index.
fn bake_missions(out: &Path) -> Vec<(String, String)> {
    let dir = Path::new("../../missions");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut missions: Vec<(String, vehicle_yaml::mission::Mission)> = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries {
            let path = entry.expect("read missions dir").path();
            if path.extension().and_then(|s| s.to_str()) != Some("yaml") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            if stem.is_empty()
                || !stem
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
            {
                panic!("missions/{stem}.yaml: name must be alphanumeric/_/- (from filename)");
            }
            let raw = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            let m = vehicle_yaml::mission::load_mission(&stem, &raw)
                .unwrap_or_else(|e| panic!("{e}"));
            for w in &m.warnings {
                println!("cargo:warning=missions/{w}");
            }
            let cap = cybflight_core::trajectory_planning::MAX_PIECES;
            assert!(
                m.waypoints.len() <= cap,
                "missions/{stem}.yaml: {} pieces exceeds MAX_PIECES = {cap} \
                 (cybflight_core::trajectory_planning)",
                m.waypoints.len(),
            );
            missions.push((stem, m));
        }
    }
    // Deterministic order — the persisted mission_profile index refers to it.
    missions.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// Auto-generated by build.rs from missions/*.yaml. Do not edit.\n\n",
    );
    if missions.is_empty() {
        // Only outer_mpc builds compile this include; make the failure
        // speak the fix instead of tripping opaque const asserts.
        code.push_str(
            "compile_error!(\"no mission YAMLs found in missions/ — outer_mpc builds \
             require at least one (drop the offline planner's output file there)\");\n",
        );
        fs::write(out.join("missions.rs"), code).expect("write missions.rs");
        return Vec::new();
    }

    use std::fmt::Write as _;
    let mut max_pieces = 1usize;
    for (i, (name, m)) in missions.iter().enumerate() {
        max_pieces = max_pieces.max(m.waypoints.len());
        let n = m.waypoints.len();
        let _ = writeln!(code, "static M{i}_WP: [[f32; 3]; {n}] = [");
        for w in &m.waypoints {
            let _ = writeln!(code, "    [{:?}f32, {:?}f32, {:?}f32],", w[0], w[1], w[2]);
        }
        code.push_str("];\n");
        let _ = writeln!(code, "static M{i}_TS: [f32; {n}] = [");
        for t in &m.timestamps {
            let _ = writeln!(code, "    {t:?}f32,");
        }
        code.push_str("];\n");
        let headings_ref = match &m.headings {
            Some(h) => {
                let _ = writeln!(code, "static M{i}_HD: [f32; {n}] = [");
                for psi in h {
                    let _ = writeln!(code, "    {psi:?}f32,");
                }
                code.push_str("];\n");
                format!("Some(&M{i}_HD)")
            }
            None => "None".to_string(),
        };
        let _ = writeln!(
            code,
            "/// Baked from `missions/{name}.yaml`.\n\
             pub static PROFILE_{i}: MissionProfile = MissionProfile {{\n\
             \x20   name: {name:?},\n\
             \x20   env: {:?},\n\
             \x20   variant: {:?},\n\
             \x20   speed: {:?},\n\
             \x20   start_pos: [{:?}f32, {:?}f32, {:?}f32],\n\
             \x20   waypoints: &M{i}_WP,\n\
             \x20   timestamps: &M{i}_TS,\n\
             \x20   headings: {headings_ref},\n\
             \x20   lookahead: {},\n\
             \x20   yaw_lookahead_dt_s: {:?}f32,\n\
             \x20   yaw_lookahead_max_rate_rad_s: {:?}f32,\n\
             \x20   flatness_map: FlatnessMap::{},\n\
             }};",
            m.env, m.variant, m.speed, m.start[0], m.start[1], m.start[2],
            m.lookahead, m.yaw_lookahead_dt_s, m.yaw_lookahead_max_rate_rad_s,
            match m.flatness_map {
                vehicle_yaml::mission::FlatnessMapKind::TiltYaw => "TiltYaw",
                vehicle_yaml::mission::FlatnessMapKind::TrueYaw => "TrueYaw",
            },
        );
    }
    code.push_str("\npub static PROFILES: &[&MissionProfile] = &[\n");
    for i in 0..missions.len() {
        let _ = writeln!(code, "    &PROFILE_{i},");
    }
    code.push_str("];\n\n");
    let _ = writeln!(
        code,
        "/// Largest piece count across the baked missions (planner scratch\n\
         /// arrays are sized to this; bounded at bake by core MAX_PIECES).\n\
         pub const OFFLINE_MAX_PIECES: usize = {max_pieces};"
    );

    // A build that compiles the mission table (outer_mpc) with a known
    // position source MUST have at least one mission of that env — the
    // per-env boot default would otherwise silently point at a
    // wrong-scale mission (e.g. an outdoor course inside a mocap room).
    if std::env::var("CARGO_FEATURE_OUTER_MPC").is_ok() {
        let need_env = if std::env::var("CARGO_FEATURE_EST_POS_MOCAP").is_ok() {
            Some("indoor")
        } else if std::env::var("CARGO_FEATURE_EST_POS_GPS").is_ok() {
            Some("outdoor")
        } else {
            None
        };
        if let Some(env) = need_env {
            assert!(
                missions.iter().any(|(_, m)| m.env == env),
                "no {env} mission in missions/ — this outer_mpc build's position \
                 source implies env={env}, and the boot default must be a mission \
                 of that env. Add a missions/<name>.yaml with `env: {env}`."
            );
        }
    }

    // Per-env boot defaults resolve by the mission's `env:` FIELD (never
    // by filename — a mislabeled file must not smuggle the wrong scale in).
    let default_for = |env: &str| -> usize {
        missions
            .iter()
            .position(|(n, m)| m.env == env && n == &format!("{env}_splits_slow"))
            .or_else(|| missions.iter().position(|(_, m)| m.env == env))
            // Only reachable when the build compiles no mission consumer
            // for this env (checked above for outer_mpc builds).
            .unwrap_or(0)
    };
    let _ = writeln!(
        code,
        "/// Per-env boot defaults, resolved by the mission's `env:` field:\n\
         /// `<env>_splits_slow` when present, else the first mission of that\n\
         /// env (guaranteed to exist for the active build env by the bake).\n\
         pub const DEFAULT_PROFILE_INDEX_INDOOR: u8 = {};\n\
         pub const DEFAULT_PROFILE_INDEX_OUTDOOR: u8 = {};",
        default_for("indoor"),
        default_for("outdoor"),
    );

    fs::write(out.join("missions.rs"), code).expect("write missions.rs");
    missions.into_iter().map(|(n, m)| (n, m.env)).collect()
}

/// Parse every CSV under `data/thrust_tables/` and emit `$OUT_DIR/thrust_tables.rs`.
///
/// CSV format (matches `tmp/thrust_map/code/thrust_map.cpp`):
///   line 1: `map_size, thrust_min, thrust_max, voltage_min, voltage_max, ...`
///           (extra trailing zeros padded to map_size columns are ignored)
///   lines 2..1+map_size: each row is `map_size` comma-separated f32 values,
///           indexed `grid[row=i_voltage][col=i_thrust]`.
///
/// **Thrust convention.** The bench rig measures *collective* thrust of all
/// `N_MOTORS` rotors running at the same command. INDI's linearization works
/// in *single-rotor* units (`u * per_motor_max_n` is one motor's force in N).
/// To match conventions, we divide the header `thrust_min` / `thrust_max` by
/// `N_MOTORS` before constructing the `ThrustTable`. The grid values are
/// commands and stay unchanged: one motor running at command `c` produces
/// `1/N_MOTORS` of the collective force the rig saw at that command.
/// Assumes all motors are identical (same param/dynamics) — fine for a
/// symmetric quad; revisit this for asymmetric airframes.
///
/// Build-time validation:
///   * `map_size == 50` (must match `cybflight_core::indi::linearization::TABLE_N`);
///   * thrust/voltage ranges are finite + monotone increasing;
///   * every grid cell parses as f32 and is finite;
///   * grid is non-decreasing along the thrust axis (row-wise) — this is the
///     monotonicity assumption that `ThrustTable::invert` relies on.
///
/// Build fails if any check fails. The MCU never parses CSV at runtime.
///
/// Returns `(csv_stem, CONST_NAME, per_rotor_thrust_max_n)` for every
/// baked table so the vehicle bake can resolve a YAML
/// `thrust_model.table` stem to its generated static AND cross-check the
/// table's thrust axis against the airframe's `max_thrust_n`.
fn bake_thrust_tables(out: &Path) -> Vec<(String, String, f64)> {
    const N: usize = 50; // matches TABLE_N in cybflight_core::indi::linearization
    // Matches `cybflight_core::indi::controller::NU`. Kept as a local const
    // because build.rs can't depend on the runtime crate; bump both together
    // if the actuator count ever changes.
    const N_MOTORS: usize = 4;

    let dir = Path::new("data/thrust_tables");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut emitted = String::new();
    emitted.push_str("// Auto-generated by build.rs from data/thrust_tables/*.csv.\n");
    emitted.push_str("// Do not edit by hand.\n\n");

    let mut baked: Vec<(String, String, f64)> = Vec::new();

    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => {
            // No data dir → emit an empty module. Firmware that doesn't need
            // a baked table builds fine.
            fs::write(out.join("thrust_tables.rs"), &emitted).unwrap();
            return baked;
        }
    };

    for entry in entries {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("csv") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        let const_name = stem
            .to_uppercase()
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
            .collect::<String>();

        let raw = fs::read_to_string(&path).expect("read thrust map csv");
        let mut lines = raw.lines().filter(|l| !l.trim().is_empty());

        // Header.
        let header = lines.next().expect("thrust map: missing header");
        let mut hdr = header.split(',').map(|s| s.trim());
        let map_size: usize = hdr
            .next()
            .expect("thrust map: missing map_size")
            .parse::<f64>()
            .expect("thrust map: map_size not a number") as usize;
        let thrust_min: f64 = hdr.next().expect("missing thrust_min").parse().unwrap();
        let thrust_max: f64 = hdr.next().expect("missing thrust_max").parse().unwrap();
        let voltage_min: f64 = hdr.next().expect("missing voltage_min").parse().unwrap();
        let voltage_max: f64 = hdr.next().expect("missing voltage_max").parse().unwrap();

        assert_eq!(
            map_size,
            N,
            "thrust map {}: expected {N}×{N} grid, got {map_size}",
            path.display()
        );
        assert!(
            thrust_max > thrust_min,
            "thrust map {}: thrust range degenerate",
            path.display()
        );
        assert!(
            voltage_max > voltage_min,
            "thrust map {}: voltage range degenerate",
            path.display()
        );

        // Collective → per-rotor conversion. See module doc on `bake_thrust_tables`.
        let thrust_min = thrust_min / N_MOTORS as f64;
        let thrust_max = thrust_max / N_MOTORS as f64;

        // Rows.
        let mut grid = [[0.0_f32; N]; N];
        for (row, row_buf) in grid.iter_mut().enumerate() {
            let line = lines
                .next()
                .unwrap_or_else(|| panic!("thrust map {}: row {row} missing", path.display()));
            let cols: Vec<&str> = line.split(',').take(N).collect();
            assert_eq!(
                cols.len(),
                N,
                "thrust map {}: row {row} has {} cols, expected {N}",
                path.display(),
                cols.len()
            );
            let mut prev = f32::NEG_INFINITY;
            for (col, s) in cols.iter().enumerate() {
                let v: f32 = s.trim().parse().unwrap_or_else(|_| {
                    panic!(
                        "thrust map {}: row {row} col {col} not f32: {s:?}",
                        path.display()
                    )
                });
                assert!(
                    v.is_finite(),
                    "thrust map {}: row {row} col {col} not finite",
                    path.display()
                );
                assert!(
                    v >= prev - 1e-3,
                    "thrust map {}: row {row} not monotone in thrust at col {col}: {prev} → {v}",
                    path.display()
                );
                prev = v;
                row_buf[col] = v;
            }
        }

        // Emit the static.
        emitted.push_str(&format!(
            "/// Baked from `data/thrust_tables/{stem}.csv` at build time.\n"
        ));
        emitted.push_str(&format!(
            "pub static {const_name}: ::cybflight_core::indi::thrust_table::ThrustTable<{N}> = match \
             ::cybflight_core::indi::thrust_table::ThrustTable::<{N}>::new(\n    [\n"
        ));
        for row in &grid {
            emitted.push_str("        [");
            for (j, v) in row.iter().enumerate() {
                if j > 0 {
                    emitted.push_str(", ");
                }
                emitted.push_str(&format!("{:e}_f32", v));
            }
            emitted.push_str("],\n");
        }
        emitted.push_str("    ],\n");
        emitted.push_str(&format!("    {thrust_min}_f32,\n"));
        emitted.push_str(&format!("    {thrust_max}_f32,\n"));
        emitted.push_str(&format!("    {voltage_min}_f32,\n"));
        emitted.push_str(&format!("    {voltage_max}_f32,\n"));
        emitted.push_str(") {\n    Some(t) => t,\n    None => panic!(\"baked thrust table failed validation\"),\n};\n\n");
        baked.push((stem, const_name, thrust_max));
    }

    fs::write(out.join("thrust_tables.rs"), emitted).expect("write thrust_tables.rs");
    baked
}

/// Parse `vehicles/$VEHICLE.yaml` (workspace root), validate it against the
/// parameter registry, and emit `$OUT_DIR/baked_params.rs` — a full
/// (name, value) snapshot of every schema parameter.
///
/// Identity enforcement: the `airframe` section is required and fully
/// structured (serde `deny_unknown_fields`, no defaults) — a missing mass,
/// motor, or inertia entry is a BUILD error, which is the "no default
/// mass" rule from docs/param_redesign_plan.md. `tuning` keys are checked
/// against the live registry via `set_named`, so a typo'd parameter name
/// is also a build error.
mod vehicle_bake {
    use std::fmt::Write as _;
    use std::path::Path;

    use cybflight_core::param_registry::{ParamGroup, ParamName};
    use cybflight_core::params::{FirmwareConfig, PARAM_COUNT};
    use vehicle_yaml::ThrustModelYaml;

    /// Env var treated as unset when absent OR empty — a blank
    /// `POS_SOURCE=` line in a .env must not count as a deliberate
    /// override (it would silently downgrade guard errors to warnings).
    fn env_nonempty(key: &str) -> Option<String> {
        std::env::var(key).ok().filter(|v| !v.is_empty())
    }

    pub fn run(out: &Path, tables: &[(String, String, f64)], missions: &[(String, String)]) {
        println!("cargo:rerun-if-env-changed=VEHICLE");
        let vehicle_env = env_nonempty("VEHICLE");
        let vehicle = vehicle_env.clone().unwrap_or_else(|| {
            // Deliberately a warning, not a hard error: bare `cargo check`
            // and rust-analyzer have no .env. `just` loads .env, so real
            // builds always set VEHICLE; the baked name is also logged at
            // boot and shown in the shell banner, so a wrong-vehicle
            // flash is detectable on the bench. sakura_vicon matches the
            // crate's default feature set (board_sakurah743 +
            // est_pos_mocap), so the fallback bake is guard-consistent.
            println!(
                "cargo:warning=VEHICLE not set — baking default vehicle 'sakura_vicon' \
                 (set VEHICLE in .env or the environment for real builds)"
            );
            "sakura_vicon".into()
        });
        let yaml_path = Path::new("../../vehicles").join(format!("{vehicle}.yaml"));
        println!("cargo:rerun-if-changed={}", yaml_path.display());
        let raw = std::fs::read_to_string(&yaml_path).unwrap_or_else(|e| {
            panic!(
                "VEHICLE={vehicle}: cannot read {} ({e}). Available vehicles \
                 live in vehicles/*.yaml at the workspace root.",
                yaml_path.display()
            )
        });
        // Shared loader (also used by the sim baseline): identity presence,
        // tuning-key existence, and range checks all happen here — any
        // violation fails the build.
        let loaded = vehicle_yaml::load(&vehicle, &raw).unwrap_or_else(|e| panic!("{e}"));
        let cfg = &loaded.params;

        // Pin-what-you-fly nudge: these keys are physically determined by
        // the airframe hardware (motors/props/battery/install), so a real
        // vehicle should state them explicitly rather than inherit schema
        // defaults that may be retuned later. Warning, not error — the
        // zero-config bring-up path stays usable.
        const HW_COUPLED_KEYS: &[&str] = &[
            "m0_tau",
            "m1_tau",
            "m2_tau",
            "m3_tau",
            "m0_omega_max",
            "m1_omega_max",
            "m2_omega_max",
            "m3_omega_max",
            "m0_g2_ry",
            "m1_g2_ry",
            "m2_g2_ry",
            "m3_g2_ry",
            "batt_nominal_v",
            "batt_min_v",
            "batt_max_v",
            "imu_accel_lpf_hz",
            "imu_gyro_lpf_hz",
            // IMU-rate coupled: the schema default (1) is only right for
            // `imu_1khz` vehicles. An 8 kHz vehicle that inherits it runs
            // INDI 1:1 at 8 kHz — the step exceeds the 125 µs period, the
            // reader misses DRDY and the IWDG feeder starves.
            "indi_ctrl_div",
            // Position-source coupled: the schema default (1 m) is
            // mocap-sized. A GPS vehicle that inherits it hard-rejects
            // healthy fast-flight frames, so every vehicle must state it.
            "eskf_max_pos_jump_m",
            // Pack-coupled: the cell-count ceiling is a fact about the
            // battery this airframe flies, and a pack above the default
            // 8S would otherwise be silently clamped rather than
            // reported.
            "batt_max_cells",
            // Arena geometry. `fence_enable` alone was guarded, so a
            // vehicle could switch the fence ON and silently inherit
            // someone else's room dimensions.
            "fence_x_m",
            "fence_y_m",
            "fence_z_max_m",
            "fence_z_min_m",
            // Transmitter-coupled: endpoints come from the TX's servo
            // travel and the channel map from its mixer. Inheriting them
            // mis-scales every stick and can put the arm switch on the
            // wrong channel.
            "rc_min_us",
            "rc_mid_us",
            "rc_max_us",
            "rc_arm_channel",
            "rc_arm_threshold_us",
            // Site-coupled: the envelope is the flying area's dimensions,
            // and gravity varies with latitude.
            "fence_enable",
            "gravity_m_s2",
            // Chemistry-coupled: a Li-ion pack needs a different
            // per-cell detection voltage than LiPo/LiHV.
            "batt_cell_detect_v",
        ];
        // Install-coupled only on a mocap build — camera count, volume
        // size and marker spread move the sigmas, and the staleness
        // window is coupled to the stream rate. Gated so GPS vehicles
        // are not nagged about a guard they never construct.
        const MOCAP_INSTALL_KEYS: &[&str] = &[
            "eskf_mocap_pos_std",
            "eskf_mocap_att_std",
            "eskf_mocap_stale_s",
            "eskf_mocap_reanchor_m",
        ];
        let mocap = std::env::var("CARGO_FEATURE_EST_POS_MOCAP").is_ok();
        for key in HW_COUPLED_KEYS
            .iter()
            .chain(MOCAP_INSTALL_KEYS.iter().filter(|_| mocap))
        {
            if !loaded.tuning_keys.contains(*key) {
                println!(
                    "cargo:warning=vehicle {vehicle}: hardware-coupled key '{key}' not \
                     pinned in tuning: — schema default applies"
                );
            }
        }

        check_build_section(&vehicle, vehicle_env.is_some(), loaded.build.as_ref());

        // Resolve the vehicle's default mission name to a baked-table
        // index. Unknown name = hard error (a typo, same class as an
        // unknown tuning key). Env-incompatible with the ACTIVE build env
        // = error, downgraded to warn+fallback under the same conditions
        // as the build-section guard: POS_SOURCE env override (deliberate
        // dev build of the other environment), VEHICLE_GUARD=off (the
        // check-all matrix), or no explicit VEHICLE (rust-analyzer/bare
        // cargo check fallback).
        let build_env = if std::env::var("CARGO_FEATURE_EST_POS_MOCAP").is_ok() {
            Some("indoor")
        } else if std::env::var("CARGO_FEATURE_EST_POS_GPS").is_ok() {
            Some("outdoor")
        } else {
            None
        };
        let default_mission_idx: Option<usize> = loaded.default_mission.as_ref().and_then(|name| {
            let Some(idx) = missions.iter().position(|(n, _)| n == name) else {
                let available: Vec<&str> = missions.iter().map(|(n, _)| n.as_str()).collect();
                panic!(
                    "VEHICLE={vehicle}: default_mission {name:?} has no \
                     missions/{name}.yaml — available: {available:?}"
                );
            };
            let env = &missions[idx].1;
            match build_env {
                Some(be) if env != be => {
                    let downgrade = env_nonempty("POS_SOURCE").is_some()
                        || std::env::var("VEHICLE_GUARD").map(|v| v == "off").unwrap_or(false)
                        || vehicle_env.is_none();
                    if downgrade {
                        println!(
                            "cargo:warning=vehicle {vehicle}: default_mission {name:?} is \
                             env={env} but this build is {be} — falling back to the {be} \
                             default mission"
                        );
                        None
                    } else {
                        panic!(
                            "VEHICLE={vehicle}: default_mission {name:?} is env={env} but \
                             the build's position source implies {be} — fix the vehicle's \
                             default_mission or build.pos_source"
                        );
                    }
                }
                _ => Some(idx),
            }
        });
        let default_mission_expr = match default_mission_idx {
            Some(i) => format!("Some({i}u8)"),
            None => "None".to_string(),
        };

        // The thrust model is REQUIRED for a firmware bake — it is exactly
        // as airframe-bound as mass (the same "no default mass" rule): a
        // new vehicle must never silently inherit another airframe's motor
        // curve. (The field is optional only at the parse level, for the
        // sim baseline which supplies its own analytic model.)
        let thrust_model = loaded.thrust_model.as_ref().unwrap_or_else(|| {
            panic!(
                "VEHICLE={vehicle}: vehicles/{vehicle}.yaml is missing the REQUIRED \
                 airframe.thrust_model. Add e.g.:\n\
                 \x20 thrust_model: {{ type: table, table: a2rl_0114 }}\n\
                 or an analytic model:\n\
                 \x20 thrust_model: {{ type: quadratic, k: 0.518 }}"
            )
        });
        let (model_expr, nonlinearity_k): (String, f32) = match thrust_model {
            ThrustModelYaml::Table { table } => {
                let (const_name, table_thrust_max) = tables
                    .iter()
                    .find(|(stem, _, _)| stem == table)
                    .map(|(_, c, tmax)| (c.clone(), *tmax))
                    .unwrap_or_else(|| {
                        let available: Vec<&str> =
                            tables.iter().map(|(s, _, _)| s.as_str()).collect();
                        panic!(
                            "VEHICLE={vehicle}: thrust_model.table {table:?} has no CSV under \
                             crates/cybflight/data/thrust_tables/ — available: {available:?}"
                        )
                    });
                // Airframe ↔ table binding check (previously a commented-out
                // boot-time defmt::panic in indi_task.rs): the table's
                // per-rotor thrust axis must match the airframe's
                // max_thrust_n, else INDI's u-axis scaling is silently
                // wrong and the drone has a fraction of the authority WLS
                // thinks it has. A warning, not an error: a deliberately
                // de-rated max_thrust_n against a stand-measured table
                // (e.g. leader_1khz, 10 N vs the 12.6 N a2rl_0114 axis) is
                // a legitimate tune, so the bake only flags the mismatch.
                for (i, motor) in cfg.airframe.motors.iter().enumerate() {
                    let pm = motor.max_thrust_n as f64;
                    let rel_err = ((pm - table_thrust_max) / table_thrust_max).abs();
                    if rel_err >= 0.10 {
                        println!(
                            "cargo:warning=vehicle {vehicle}: thrust table {table:?} per-rotor \
                             max ({table_thrust_max:.2} N) and motor {i} max_thrust_n \
                             ({pm:.2} N) disagree by {:.0}% (>=10%) — accepted as a \
                             deliberate de-rate; re-bake the table if this is not intended",
                            rel_err * 100.0,
                        );
                    }
                }
                (
                    format!(
                        "::cybflight_core::indi::linearization::ThrustModel::Table(\
                         &crate::thrust_tables::{const_name})"
                    ),
                    // Table mode: the table itself encodes the curve; the
                    // nonlinearity fallback k is unused (0.0).
                    0.0,
                )
            }
            ThrustModelYaml::Quadratic { k } => (
                "::cybflight_core::indi::linearization::ThrustModel::Quadratic".into(),
                *k,
            ),
            ThrustModelYaml::SqrtSquared { k } => (
                "::cybflight_core::indi::linearization::ThrustModel::SqrtSquared".into(),
                *k,
            ),
        };
        // The YAML accepts k in [0, 1] but ThrustLinearization silently
        // clamps to [0.025, 1.0] at runtime — surface the discrepancy at
        // bake instead of letting a declared value quietly become the
        // clamped one. Only the k→0 floor can bite now; the upper bound
        // is the physical limit of the curve.
        if !matches!(thrust_model, ThrustModelYaml::Table { .. })
            && !(0.025..=1.0).contains(&nonlinearity_k)
        {
            println!(
                "cargo:warning=vehicle {vehicle}: thrust_model k = {nonlinearity_k} is \
                 outside the linearization's effective range [0.025, 1.0] and will be \
                 clamped at runtime"
            );
        }

        // Identity is how a mis-flashed board is caught before takeoff, so
        // its absence is worth a nudge — but not a hard error, since the
        // sim baseline and older vehicles predate the field.
        let airframe_name_expr = match &loaded.airframe_name {
            Some(n) => format!("Some({n:?})"),
            None => {
                println!(
                    "cargo:warning=vehicle {vehicle}: no airframe.name — this firmware \
                     cannot report which physical airframe it was built for, so a \
                     board flashed with the wrong vehicle's binary (wrong mass / \
                     inertia / motor geometry, wrong mocap subject) will not be \
                     detectable on the ground"
                );
                "None".to_string()
            }
        };

        let mut code = String::new();
        let _ = writeln!(
            code,
            "// Auto-generated by build.rs from vehicles/{vehicle}.yaml. Do not edit.\n\
             /// The vehicle FILE this firmware was baked from (= YAML stem).\n\
             pub const BAKED_VEHICLE: &str = {vehicle:?};\n\
             /// The PHYSICAL AIRFRAME this firmware was baked for\n\
             /// (`airframe.name`), or None if the YAML declares none.\n\
             ///\n\
             /// Distinct from `BAKED_VEHICLE`: one airframe can have\n\
             /// several vehicle files (an indoor and an outdoor build of\n\
             /// the same machine). This is the name that must agree with\n\
             /// the mocap rigid body and with the cybgcs fleet roster, so\n\
             /// reporting it is what lets a board flashed with the wrong\n\
             /// airframe's firmware be caught on the ground.\n\
             pub const BAKED_AIRFRAME_NAME: Option<&str> = {airframe_name_expr};\n\
             /// Full (name, value) snapshot of every schema parameter.\n\
             pub static BAKED_PARAMS: [(&str, f32); {PARAM_COUNT}] = ["
        );
        for idx in 0..PARAM_COUNT {
            let name = ParamName::of::<FirmwareConfig>(idx).expect("param name");
            let v = cfg.param_get(idx).expect("param value").as_f32();
            let _ = writeln!(code, "    ({:?}, {:?}_f32),", name.as_str(), v);
        }
        code.push_str("];\n");
        emit_thrust_model(&mut code, &vehicle, &model_expr, nonlinearity_k);
        let _ = writeln!(
            code,
            "/// Index of this vehicle's `default_mission` in the baked mission\n\
             /// table (None = YAML declared none, or an env-overridden build\n\
             /// fell back to the per-env default). Env-validated at bake.\n\
             pub const BAKED_DEFAULT_MISSION_INDEX: Option<u8> = {default_mission_expr};"
        );

        // Fixed ENU anchor, if the YAML declares one. `f64` for lat/lon:
        // an f32 latitude has a ~0.6 m ULP at mid-latitudes, which would
        // throw away exactly the accuracy the RTK-fixed anchor exists to
        // provide. This is why it is a dedicated `origin:` section rather
        // than three `tuning:` keys.
        let origin_expr = match loaded.origin {
            Some(o) => format!(
                "Some(BakedOrigin {{ lat_deg: {:?}_f64, lon_deg: {:?}_f64, alt_msl_m: {:?}_f32 }})",
                o.lat_deg, o.lon_deg, o.alt_msl_m
            ),
            None => "None".to_string(),
        };
        let _ = writeln!(
            code,
            "/// A fixed geodetic ENU anchor declared by the vehicle YAML.\n\
             #[derive(Clone, Copy, Debug)]\n\
             pub struct BakedOrigin {{\n\
             \x20   pub lat_deg: f64,\n\
             \x20   pub lon_deg: f64,\n\
             \x20   pub alt_msl_m: f32,\n\
             }}\n\
             /// Fixed ENU origin from `vehicles/{vehicle}.yaml` (`origin:`).\n\
             /// `None` → the estimator anchors on the first RTK-fixed PVT.\n\
             pub const BAKED_ORIGIN: Option<BakedOrigin> = {origin_expr};"
        );
        emit_cost_policy(&mut code, &vehicle, loaded.mpc_cost_policy.as_deref());
        std::fs::write(out.join("baked_params.rs"), code).expect("write baked_params.rs");
    }

    /// Bake the learned-cost policy the vehicle YAML names
    /// (`mpc_cost_policy: <stem>` → `data/cost_policies/<stem>.bin`, the
    /// flat `nn::Mlp` export written by `tools/train_cost_policy.py`:
    /// LE `u32 magic`, `u32 format`, `u32 map_version`, `u32 n_layers`,
    /// `n_layers × (u32 in, u32 out)`, then per layer `W(out,in)`
    /// row-major + `b(out)` as f32). No key = no policy baked, no flash
    /// cost. The header is validated against
    /// `cost_adapt::{COST_MAP_VERSION, OBS_DIM, NZ, POLICY_MAX_WIDTH}` so
    /// a stale or mismatched export fails the BUILD, not the flight.
    /// Weights are emitted bit-exact (`f32::from_bits`) into an
    /// initialised static (`.rodata`, deliberately not zero-init — see
    /// the 8 kHz `.bss` boot-loop history).
    fn emit_cost_policy(code: &mut String, vehicle: &str, stem: Option<&str>) {
        use cybflight_core::mpc::cost_adapt::{
            COST_MAP_VERSION, NZ, OBS_DIM, POLICY_MAX_WIDTH,
        };
        println!("cargo:rerun-if-changed=data/cost_policies");
        const SHAPE_TY: &str = "::cybflight_core::nn::mlp::LayerShape";
        let Some(stem) = stem else {
            let _ = writeln!(
                code,
                "/// Learned cost policy: vehicles/{vehicle}.yaml declares no\n\
                 /// `mpc_cost_policy:` — nothing baked.\n\
                 pub const BAKED_COST_POLICY_NAME: Option<&str> = None;\n\
                 pub static BAKED_COST_POLICY: Option<(&[f32], &[{SHAPE_TY}])> = None;"
            );
            return;
        };
        let path = Path::new("data/cost_policies").join(format!("{stem}.bin"));
        let bytes = std::fs::read(&path).unwrap_or_else(|e| {
            panic!(
                "VEHICLE={vehicle}: mpc_cost_policy {stem:?} has no {} ({e}) — \
                 export one with tools/train_cost_policy.py and copy it there",
                path.display()
            )
        });
        if !Path::new("data/cost_policies").join(format!("{stem}.md")).exists() {
            println!(
                "cargo:warning=vehicle {vehicle}: cost policy {stem:?} has no provenance \
                 sidecar data/cost_policies/{stem}.md — record the training config, sim \
                 numbers and observation units (V_SCALE/V_ERR_SCALE/RATE_SCALE/OBS_CLAMP) \
                 the checkpoint assumes"
            );
        }
        let u32_at = |i: usize| -> usize {
            let b: [u8; 4] = bytes
                .get(i..i + 4)
                .and_then(|s| s.try_into().ok())
                .unwrap_or_else(|| {
                    panic!("VEHICLE={vehicle}: {} truncated at byte {i}", path.display())
                });
            u32::from_le_bytes(b) as usize
        };
        // Magic + format + map revision, ahead of the shape table. The
        // shape checks below cannot tell a checkpoint trained against a
        // different weight map from a current one — v18 → v20 changed a
        // fence constant and left every dimension identical — so the
        // export carries the map revision and the bake refuses anything
        // that is not the one this firmware computes weights with.
        const MAGIC: usize = 0x5043_4643; // b"CFCP" little-endian
        const FORMAT: usize = 1;
        assert_eq!(
            u32_at(0),
            MAGIC,
            "VEHICLE={vehicle}: {} is not a cost-policy export, or predates the versioned \
             header — re-export it with tools/train_cost_policy.py",
            path.display()
        );
        assert_eq!(
            u32_at(4),
            FORMAT,
            "VEHICLE={vehicle}: {} uses export format {}, this build reads {FORMAT}",
            path.display(),
            u32_at(4)
        );
        let map_version = u32_at(8);
        assert_eq!(
            map_version as u32, COST_MAP_VERSION,
            "VEHICLE={vehicle}: policy {stem:?} was trained against cost-map revision \
             {map_version}, this firmware computes weights with revision {COST_MAP_VERSION} \
             — the same z means something different under the two maps \
             (docs/learned_mpc_cost_deploy.md). Re-train or re-export against the current map."
        );
        const HDR: usize = 12;
        let n_layers = u32_at(HDR);
        assert!(
            (1..=16).contains(&n_layers),
            "VEHICLE={vehicle}: {} header claims {n_layers} layers",
            path.display()
        );
        let shapes: Vec<(usize, usize)> = (0..n_layers)
            .map(|l| (u32_at(HDR + 4 + 8 * l), u32_at(HDR + 8 + 8 * l)))
            .collect();
        assert_eq!(
            shapes[0].0, OBS_DIM,
            "VEHICLE={vehicle}: policy {stem:?} input width {} != cost_adapt::OBS_DIM \
             {OBS_DIM} — stale export for a different observation layout",
            shapes[0].0
        );
        assert_eq!(
            shapes[n_layers - 1].1, NZ,
            "VEHICLE={vehicle}: policy {stem:?} output width {} != cost_adapt::NZ {NZ}",
            shapes[n_layers - 1].1
        );
        for w in shapes.windows(2) {
            assert_eq!(
                w[0].1, w[1].0,
                "VEHICLE={vehicle}: policy {stem:?} layer chain mismatch ({} out vs {} in)",
                w[0].1, w[1].0
            );
            assert!(
                w[0].1 <= POLICY_MAX_WIDTH,
                "VEHICLE={vehicle}: policy {stem:?} hidden width {} > POLICY_MAX_WIDTH \
                 {POLICY_MAX_WIDTH}",
                w[0].1
            );
        }
        let n_weights: usize = shapes.iter().map(|(i, o)| i * o + o).sum();
        let body = &bytes[HDR + 4 + 8 * n_layers..];
        assert_eq!(
            body.len(),
            4 * n_weights,
            "VEHICLE={vehicle}: policy {stem:?} carries {} weight bytes, shapes need {}",
            body.len(),
            4 * n_weights
        );
        let _ = writeln!(
            code,
            "/// Learned cost policy baked from data/cost_policies/{stem}.bin\n\
             /// (vehicles/{vehicle}.yaml `mpc_cost_policy:`). Flash cost {} bytes.\n\
             pub const BAKED_COST_POLICY_NAME: Option<&str> = Some({stem:?});\n\
             static BAKED_COST_POLICY_SHAPES: [{SHAPE_TY}; {n_layers}] = [",
            4 * n_weights,
        );
        for (i, o) in &shapes {
            let _ = writeln!(code, "    {SHAPE_TY}::new({i}, {o}),");
        }
        let _ = writeln!(
            code,
            "];\nstatic BAKED_COST_POLICY_WEIGHTS: [f32; {n_weights}] = ["
        );
        for (k, c) in body.chunks_exact(4).enumerate() {
            let bits = u32::from_le_bytes(c.try_into().unwrap());
            let v = f32::from_bits(bits);
            assert!(
                v.is_finite(),
                "VEHICLE={vehicle}: policy {stem:?} weight {k} is non-finite"
            );
            let _ = write!(code, "f32::from_bits({bits:#010x}),");
            if k % 8 == 7 {
                code.push('\n');
            }
        }
        let _ = writeln!(
            code,
            "];\npub static BAKED_COST_POLICY: Option<(&[f32], &[{SHAPE_TY}])> = \
             Some((&BAKED_COST_POLICY_WEIGHTS, &BAKED_COST_POLICY_SHAPES));"
        );
    }

    fn emit_thrust_model(code: &mut String, vehicle: &str, model_expr: &str, nonlinearity_k: f32) {
        let _ = writeln!(
            code,
            "/// Thrust-to-command model declared by vehicles/{vehicle}.yaml\n\
             /// (`airframe.thrust_model`, REQUIRED at bake). Table variants\n\
             /// reference a static baked from data/thrust_tables/*.csv.\n\
             pub const BAKED_THRUST_MODEL: ::cybflight_core::indi::linearization::ThrustModel =\n\
             \x20   {model_expr};\n\
             /// Nonlinearity `k` matched to [`BAKED_THRUST_MODEL`]: the YAML's\n\
             /// `k` for analytic models, 0.0 for `Table` (the table encodes the\n\
             /// curve). Used only where `indi_nonlin_m*` params are unset.\n\
             pub const BAKED_THRUST_NONLINEARITY: f32 = {nonlinearity_k:?}_f32;"
        );
    }

    /// Cross-check the YAML `build:` section against the ACTIVE cargo
    /// features (`CARGO_FEATURE_*` env vars) — kills the historical
    /// split-brain where VEHICLE= and BOARD= were independent env vars
    /// and a mismatched pairing flashed one board's pin mappings with
    /// another vehicle's airframe params.
    ///
    /// Severity policy (mirrors the warn-not-error default-vehicle
    /// behavior above so bare `cargo check` / rust-analyzer never see a
    /// red build script):
    /// - `cargo:warning` when VEHICLE was not explicitly set, when
    ///   `VEHICLE_GUARD=off` (the check-all matrix), or when the knob's
    ///   own env var (OUTER_LOOP, POS_SOURCE, …) is set — a deliberate
    ///   dev override, already warned about by vehicle-features.
    /// - hard build error otherwise. The `board` knob NEVER downgrades
    ///   via its env var: overriding the board against the declared
    ///   vehicle is exactly the dangerous pairing; make a vehicle YAML
    ///   instead.
    fn check_build_section(
        vehicle: &str,
        vehicle_explicit: bool,
        build: Option<&vehicle_yaml::BuildYaml>,
    ) {
        println!("cargo:rerun-if-env-changed=VEHICLE_GUARD");
        for var in [
            "BOARD",
            "RC_PROTOCOL",
            "OUTER_LOOP",
            "POS_SOURCE",
            "GPS_MODEL",
            "IMU_RATE",
        ] {
            println!("cargo:rerun-if-env-changed={var}");
        }
        let Some(b) = build else {
            println!(
                "cargo:warning=vehicle {vehicle}: no build: section — feature↔vehicle \
                 consistency not checked (declare board/rc_protocol/… to enable the guard)"
            );
            return;
        };
        let guard_on = vehicle_explicit
            && std::env::var("VEHICLE_GUARD").map(|v| v != "off").unwrap_or(true);

        let active: Vec<String> = std::env::vars()
            .filter_map(|(k, _)| {
                k.strip_prefix("CARGO_FEATURE_")
                    .map(|f| f.to_ascii_lowercase())
            })
            .collect();
        let has = |f: &str| active.iter().any(|a| a == f);

        // (knob, env var, YAML-declared value, expected feature, sibling group)
        let report = |knob: &str,
                      env_var: &str,
                      declared: Option<&String>,
                      expected: Option<String>,
                      group: &[&str]| {
            let Some(expected) = expected else { return };
            // Mismatch if the expected feature is absent OR a sibling from
            // the same exclusive group is also active.
            let missing = !expected.is_empty() && !has(&expected);
            let stray: Vec<&str> = group
                .iter()
                .filter(|f| **f != expected && has(f))
                .copied()
                .collect();
            if !missing && stray.is_empty() {
                return;
            }
            // A deliberate override is one that *disagrees* with the YAML.
            // Keying off mere presence meant a stale `export POS_SOURCE=gps`
            // matching the YAML exactly still downgraded a genuine
            // board/feature split-brain to a warning — the guard disarmed
            // itself precisely when it agreed with the file it was
            // checking. `vehicle-features` has always compared values;
            // this now matches it.
            let deliberate_override = knob != "board"
                && env_nonempty(env_var)
                    .is_some_and(|v| Some(v.as_str()) != declared.map(|d| d.as_str()));
            // `expected` can legitimately be empty ("this knob value maps
            // to NO feature", e.g. gps_model: ublox) — name the semantics
            // instead of printing a cryptic "".
            let expected_desc = if expected.is_empty() {
                "no feature from this group (driver default)".to_string()
            } else {
                format!("{expected:?}")
            };
            let msg = format!(
                "vehicle {vehicle}: build.{knob} implies {expected_desc} but active \
                 features are [missing: {missing}, conflicting: {stray:?}] — \
                 feature list and vehicle YAML disagree"
            );
            if guard_on && !deliberate_override {
                panic!(
                    "{msg}\nFix the vehicle's build: section, the feature list, or \
                     set VEHICLE_GUARD=off for a deliberate mixed build."
                );
            } else {
                println!("cargo:warning={msg} (downgraded to warning)");
            }
        };

        const BOARDS: &[&str] = &["board_sakurah743", "board_foxeerh743", "board_micoair743v2"];
        const RX: &[&str] = &["rx_crsf", "rx_ghst"];
        const OUTER: &[&str] = &["outer_mpc", "outer_geometric", "outer_rate"];
        const POS: &[&str] = &["est_pos_mocap", "est_pos_gps"];

        report("board", "BOARD", b.board.as_ref(), b.board.as_ref().map(|v| format!("board_{v}")), BOARDS);
        report(
            "rc_protocol",
            "RC_PROTOCOL",
            b.rc_protocol.as_ref(),
            b.rc_protocol.as_ref().map(|v| format!("rx_{v}")),
            RX,
        );
        report(
            "outer_loop",
            "OUTER_LOOP",
            b.outer_loop.as_ref(),
            b.outer_loop.as_ref().map(|v| match v.as_str() {
                "cascade" => "outer_geometric".to_string(),
                "rate" => "outer_rate".to_string(),
                _ => "outer_mpc".to_string(),
            }),
            OUTER,
        );
        report(
            "pos_source",
            "POS_SOURCE",
            b.pos_source.as_ref(),
            b.pos_source.as_ref().map(|v| format!("est_pos_{v}")),
            POS,
        );
        report(
            "gps_model",
            "GPS_MODEL",
            b.gps_model.as_ref(),
            b.gps_model.as_ref().map(|v| {
                // Both GPS knobs are inert unless the GPS is the position
                // source: `vehicle-features` only emits these features
                // when pos_source resolves to gps, because a mocap build
                // has no reason to compile a GNSS driver. Keying off the
                // ACTIVE feature rather than the YAML value keeps a
                // pos_source disagreement to one error (from the
                // pos_source guard) instead of cascading into this one.
                if v == "unicore" && has("est_pos_gps") {
                    "gps_unicore".to_string()
                } else {
                    // ublox, or a non-GPS build = absence of gps_unicore;
                    // empty expected means "no feature required", and the
                    // sibling check still catches a stray gps_unicore.
                    String::new()
                }
            }),
            &["gps_unicore"],
        );
        report(
            "gps_dual_antenna",
            "GPS_DUAL_ANTENNA",
            b.gps_dual_antenna.as_ref(),
            b.gps_dual_antenna.as_ref().map(|v| {
                if v == "yes" && has("est_pos_gps") {
                    "gps_dual_antenna".to_string()
                } else {
                    // no, or a non-GPS build = absence of the feature; the
                    // sibling check still catches a stray one.
                    String::new()
                }
            }),
            &["gps_dual_antenna"],
        );
        // The declarations above are silently inert on a mocap build. Say
        // so, rather than let someone set `gps_model: unicore` and wonder
        // why no UM982 traffic ever appears.
        if !has("est_pos_gps")
            && (b.gps_model.is_some() || b.gps_dual_antenna.as_deref() == Some("yes"))
        {
            println!(
                "cargo:warning=vehicle {vehicle}: build.gps_model / build.gps_dual_antenna \
                 are declared but pos_source is not gps — no GNSS driver is compiled and \
                 these knobs have no effect on this build"
            );
        }
        report(
            "imu_rate",
            "IMU_RATE",
            b.imu_rate.as_ref(),
            b.imu_rate.as_ref().map(|v| {
                if v == "1khz" {
                    "imu_1khz".to_string()
                } else {
                    // 8khz = absence of imu_1khz; the sibling check still
                    // catches a stray imu_1khz (same pattern as gps_model).
                    String::new()
                }
            }),
            &["imu_1khz"],
        );
        report(
            "indi",
            "INDI",
            b.indi.as_ref(),
            b.indi.as_ref().map(|v| {
                if v == "no" {
                    "indi_off".to_string()
                } else {
                    // yes = absence of indi_off; the sibling check still
                    // catches a stray one (same pattern as imu_rate).
                    String::new()
                }
            }),
            &["indi_off"],
        );
        report(
            "plan_online",
            "PLAN_ONLINE",
            b.plan_online.as_ref(),
            b.plan_online.as_ref().map(|v| {
                if v == "yes" {
                    "plan_online".to_string()
                } else {
                    // no = absence of the feature; the sibling check
                    // still catches a stray one (same pattern as indi).
                    String::new()
                }
            }),
            &["plan_online"],
        );
    }
}
