[workspace.metadata.bin]
just = { version = "1" }

[workspace]
resolver = "3"
members = [
  "crates/cybflight",
  "crates/cybflight_core",
  "crates/bsp/sakurah743",
  "crates/bsp/foxeerh743",
  "crates/bsp/types",
  "crates/drivers",
]

[profile.release]
debug = 2
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false