[package]
name = "cybflight-core"
version = "0.1.0"
edition = "2024"
publish = false

[features]
std = ["nalgebra/std"]

[dependencies]
cybflight-params-derive = { path = "../params_derive" }
crc32fast = { version = "1.5", default-features = false }
float-cmp = { version = "0.10.0", default-features = false }
nalgebra = { version = "0.34.1", default-features = false, features = ["libm", "macros"] }
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }
flight-solver = "0.1.0"
air-filters = { version = "0.0.5", default-features = false, features = ["libm"] }
libm = "0.2"
