[registry]
global-credential-providers = ["cargo:token"]

[registries]
utadr = { index = "sparse+https://crates.yifanl.com/api/v1/crates/" }

[target.thumbv7em-none-eabihf]
rustflags = ["-C", "target-cpu=cortex-m7"]
runner = "bash tools/build.sh"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
# DEFMT_LOG = "trace"