//! Parameter registry: the runtime interface generated by
//! `#[derive(Params)]` (see the `cybflight-params-derive` crate).
//!
//! A *param group* is a struct whose tunable fields are exposed as a flat,
//! index-addressed list of named scalar parameters. Groups compose: a field
//! may itself be a group (`#[param(nested)]`), or a fixed array of groups
//! (`#[param(nested_array, prefix = "m")]` → `m0_…`, `m1_…`). Composition
//! is resolved by index arithmetic and streamed name segments — no
//! compile-time string concatenation, no heap.
//!
//! Value typing lives in [`ParamValue`]. The shell parses `f32` text, so
//! writes go through [`ParamGroup::param_set_f32`], which converts to the
//! field's native type (saturating for integers, `>= 0.5` for bools).

/// A typed parameter value, as read from a group.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ParamValue {
    F32(f32),
    U8(u8),
    U16(u16),
    /// Wide unsigned scalar, for bit masks that outgrow 16 bits. The
    /// flash blob and the shell both carry parameters as `f32`, which is
    /// exact only below 2^24, so a `U32` parameter's `max` must stay
    /// under that — see `blackbox_mute_mask`.
    U32(u32),
    Bool(bool),
}

impl ParamValue {
    /// Uniform f32 projection — used by the flash blob encoding and by
    /// shell display. Lossless for every variant (u8/u16/bool are exactly
    /// representable in f32).
    pub fn as_f32(self) -> f32 {
        match self {
            ParamValue::F32(v) => v,
            ParamValue::U8(v) => v as f32,
            ParamValue::U16(v) => v as f32,
            ParamValue::U32(v) => v as f32,
            ParamValue::Bool(v) => {
                if v {
                    1.0
                } else {
                    0.0
                }
            }
        }
    }
}

/// Shell-facing display: numeric for every variant (bools as 0/1), so
/// output is always re-parsable by `param set`.
impl core::fmt::Display for ParamValue {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            ParamValue::F32(v) => write!(f, "{v}"),
            ParamValue::U8(v) => write!(f, "{v}"),
            ParamValue::U16(v) => write!(f, "{v}"),
            ParamValue::U32(v) => write!(f, "{v}"),
            ParamValue::Bool(v) => write!(f, "{}", if *v { 1 } else { 0 }),
        }
    }
}

/// Saturating f32 → u8 (NaN and negatives → 0).
pub fn f32_to_u8(v: f32) -> u8 {
    if v.is_finite() && v > 0.0 {
        if v >= u8::MAX as f32 { u8::MAX } else { v as u8 }
    } else {
        0
    }
}

/// Saturating f32 → u16 (NaN and negatives → 0).
pub fn f32_to_u16(v: f32) -> u16 {
    if v.is_finite() && v > 0.0 {
        if v >= u16::MAX as f32 {
            u16::MAX
        } else {
            v as u16
        }
    } else {
        0
    }
}

/// Saturating f32 → u32 (NaN and negatives → 0).
///
/// Values at or above 2^24 are not exactly representable in the `f32`
/// the param plane carries, so a `U32` parameter's declared `max` is
/// what keeps the flash round-trip exact — this function only clamps.
pub fn f32_to_u32(v: f32) -> u32 {
    if v.is_finite() && v > 0.0 {
        if v >= u32::MAX as f32 {
            u32::MAX
        } else {
            v as u32
        }
    } else {
        0
    }
}

/// f32 → bool: anything ≥ 0.5 is true (tolerant of f32 round trips).
pub fn f32_to_bool(v: f32) -> bool {
    v >= 0.5
}

/// Per-parameter metadata: unit, valid range, and the first line of the
/// field's doc comment. Generated by `#[derive(Params)]` from the optional
/// `#[param(unit = "...", min = ..., max = ...)]` attributes; array fields
/// share one metadata entry across elements.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ParamMeta {
    /// Physical unit, `""` when unspecified.
    pub unit: &'static str,
    /// Inclusive lower bound; `NEG_INFINITY` when unbounded.
    pub min: f32,
    /// Inclusive upper bound; `INFINITY` when unbounded.
    pub max: f32,
    /// First line of the field's doc comment, `""` when none.
    pub doc: &'static str,
    /// True when a changed value only takes effect after a reboot
    /// (consumer captures it once at task/board init). False means the
    /// disarmed hot-reload path applies it live.
    pub reboot: bool,
}

impl ParamMeta {
    pub const UNSPEC: ParamMeta = ParamMeta {
        unit: "",
        min: f32::NEG_INFINITY,
        max: f32::INFINITY,
        doc: "",
        reboot: false,
    };

    /// Whether `v` satisfies this parameter's range constraint.
    pub fn in_range(&self, v: f32) -> bool {
        v >= self.min && v <= self.max
    }
}

/// Enum fields exposed as u8 params (`#[param(enum_u8)]`).
///
/// `from_u8` must be total — out-of-range values map to a defined
/// fallback so a stale flash image can never produce an invalid enum.
pub trait ParamEnum: Copy {
    fn to_u8(self) -> u8;
    fn from_u8(v: u8) -> Self;
}

/// Flat, index-addressed view over a struct's tunable parameters.
///
/// Generated by `#[derive(Params)]`. Indices are stable within a firmware
/// build (declaration order, depth-first through nested groups) but are
/// NOT a wire format across builds — persistent storage must go through
/// the versioned blob (or, later, the key-value store) which guards with
/// magic/version/CRC.
pub trait ParamGroup {
    /// Total number of scalar parameters in this group (nested included).
    const COUNT: usize;

    /// Read parameter `idx`. `None` if out of range.
    fn param_get(&self, idx: usize) -> Option<ParamValue>;

    /// Write parameter `idx` from an f32 (shell/text source), converting
    /// to the field's native type. Returns `false` if out of range.
    fn param_set_f32(&mut self, idx: usize, v: f32) -> bool;

    /// Metadata (unit/range/doc) for parameter `idx`.
    /// [`ParamMeta::UNSPEC`] for out-of-range indices.
    fn param_meta(idx: usize) -> ParamMeta;

    /// Resolve a full parameter name (e.g. `"m0_px"`) to its index.
    fn param_find(name: &str) -> Option<usize>;

    /// Stream the full name of parameter `idx` into `w`.
    /// Returns `Err` for out-of-range `idx` or a full buffer.
    fn param_write_name(idx: usize, w: &mut dyn core::fmt::Write) -> core::fmt::Result;

    /// Stream the dot-separated *group path* of parameter `idx` — the
    /// chain of nested field names that leads to it, e.g. `eskf.mocap_guard`
    /// for `eskf_mocap_pos_std`. Empty for a parameter declared directly on
    /// this group.
    ///
    /// Parameter *names* are flat by design (one namespace for `param set`
    /// and the flash KV store), so the structure that already exists in the
    /// config types is otherwise invisible at runtime. This exposes it, so
    /// the shell can group its output and filter by subtree instead of
    /// guessing from name prefixes — which would be wrong anyway:
    /// `eskf_mocap_pos_std` lives in `eskf.mocap_guard`, a path no prefix
    /// rule recovers.
    ///
    /// Because a group's parameters are laid out contiguously by index, a
    /// caller walking `0..COUNT` sees each path exactly once, as a run.
    fn param_write_path(idx: usize, w: &mut dyn core::fmt::Write) -> core::fmt::Result;
}

/// Sink that records only *whether* anything was written, used by the
/// derive to decide if a nested group contributes a further path segment
/// (so `eskf.filter` doesn't come out as `eskf.filter.`). Writing nothing
/// is the signal that the child holds the leaf directly.
#[derive(Default)]
pub struct PathProbe {
    pub wrote: bool,
}

impl core::fmt::Write for PathProbe {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        if !s.is_empty() {
            self.wrote = true;
        }
        Ok(())
    }
}

/// Fixed-capacity helper to materialize a param name as a `&str` —
/// convenient for shell output and tests. 48 bytes covers every
/// generated name with headroom.
pub struct ParamName {
    buf: [u8; 48],
    len: usize,
}

impl ParamName {
    pub fn of<G: ParamGroup>(idx: usize) -> Option<Self> {
        let mut n = ParamName {
            buf: [0; 48],
            len: 0,
        };
        struct W<'a>(&'a mut ParamName);
        impl core::fmt::Write for W<'_> {
            fn write_str(&mut self, s: &str) -> core::fmt::Result {
                let bytes = s.as_bytes();
                let end = self.0.len + bytes.len();
                if end > self.0.buf.len() {
                    return Err(core::fmt::Error);
                }
                self.0.buf[self.0.len..end].copy_from_slice(bytes);
                self.0.len = end;
                Ok(())
            }
        }
        G::param_write_name(idx, &mut W(&mut n)).ok()?;
        Some(n)
    }

    pub fn as_str(&self) -> &str {
        // Only &str fragments are ever appended.
        core::str::from_utf8(&self.buf[..self.len]).unwrap_or("")
    }
}

impl ParamName {
    /// Materialize the dot-separated group path of parameter `idx` (see
    /// [`ParamGroup::param_write_path`]). Empty string for a parameter
    /// declared directly on `G`.
    pub fn path_of<G: ParamGroup>(idx: usize) -> Option<Self> {
        let mut n = ParamName {
            buf: [0; 48],
            len: 0,
        };
        struct W<'a>(&'a mut ParamName);
        impl core::fmt::Write for W<'_> {
            fn write_str(&mut self, s: &str) -> core::fmt::Result {
                let bytes = s.as_bytes();
                let end = self.0.len + bytes.len();
                if end > self.0.buf.len() {
                    return Err(core::fmt::Error);
                }
                self.0.buf[self.0.len..end].copy_from_slice(bytes);
                self.0.len = end;
                Ok(())
            }
        }
        G::param_write_path(idx, &mut W(&mut n)).ok()?;
        Some(n)
    }

    /// Whether this path is inside `filter`, treating `.` `-` and `_` as
    /// interchangeable separators so the shell accepts `eskf-mocap_guard`,
    /// `eskf.mocap_guard` and plain `eskf` alike. A match must land on a
    /// segment boundary, so `mpc` never matches `mpc_weights`-style
    /// siblings by accident.
    pub fn path_matches(path: &str, filter: &str) -> bool {
        let norm = |c: u8| if c == b'-' || c == b'_' { b'.' } else { c };
        let (p, f) = (path.as_bytes(), filter.as_bytes());
        if f.len() > p.len() {
            return false;
        }
        if !p
            .iter()
            .zip(f.iter())
            .all(|(a, b)| norm(a.to_ascii_lowercase()) == norm(b.to_ascii_lowercase()))
        {
            return false;
        }
        // Full match, or the next path byte starts a new segment.
        f.len() == p.len() || p[f.len()] == b'.'
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cybflight_params_derive::Params;

    #[derive(Clone, Copy, PartialEq, Debug)]
    enum Mode {
        A,
        B,
    }
    impl ParamEnum for Mode {
        fn to_u8(self) -> u8 {
            match self {
                Mode::A => 0,
                Mode::B => 1,
            }
        }
        fn from_u8(v: u8) -> Self {
            if v == 0 { Mode::A } else { Mode::B }
        }
    }

    #[derive(Params)]
    struct Leaf {
        px: f32,
        py: f32,
        #[param(enum_u8)]
        mode: Mode,
    }

    #[derive(Params)]
    struct Root {
        #[param(key = "mass")]
        mass_kg: f32,
        #[param(keys = "kx,ky,kz")]
        gains: [f32; 3],
        #[param(keys = "g_a0,g_b0,g_a1,g_b1")]
        mat: [[f32; 2]; 2],
        #[param(nested_array, prefix = "m")]
        motors: [Leaf; 2],
        #[param(as_u16)]
        iters: usize,
        enabled: bool,
        #[param(skip)]
        _scratch: f32,
    }

    fn root() -> Root {
        Root {
            mass_kg: 0.65,
            gains: [1.0, 2.0, 3.0],
            mat: [[10.0, 11.0], [12.0, 13.0]],
            motors: [
                Leaf { px: -0.1, py: 0.1, mode: Mode::A },
                Leaf { px: 0.1, py: -0.1, mode: Mode::B },
            ],
            iters: 500,
            enabled: true,
            _scratch: 0.0,
        }
    }

    #[test]
    fn count_and_names() {
        // 1 + 3 + 4 + 2*3 + 1 + 1 = 16
        assert_eq!(Root::COUNT, 16);
        let names: Vec<_> = (0..Root::COUNT)
            .map(|i| ParamName::of::<Root>(i).unwrap().as_str().to_string())
            .collect();
        assert_eq!(names[0], "mass");
        assert_eq!(names[1..4], ["kx", "ky", "kz"]);
        assert_eq!(names[4..8], ["g_a0", "g_b0", "g_a1", "g_b1"]);
        assert_eq!(names[8..11], ["m0_px", "m0_py", "m0_mode"]);
        assert_eq!(names[11..14], ["m1_px", "m1_py", "m1_mode"]);
        assert_eq!(names[14], "iters");
        assert_eq!(names[15], "enabled");
        // Names are unique and every name round-trips through find.
        for (i, n) in names.iter().enumerate() {
            assert_eq!(Root::param_find(n), Some(i), "find({n})");
        }
        assert_eq!(Root::param_find("nope"), None);
        assert_eq!(Root::param_find("m2_px"), None);
        assert_eq!(Root::param_find("m0_nope"), None);
    }

    #[test]
    fn get_set_typed() {
        let mut r = root();
        assert_eq!(r.param_get(0), Some(ParamValue::F32(0.65)));
        assert_eq!(r.param_get(6), Some(ParamValue::F32(12.0))); // mat[1][0]
        assert_eq!(r.param_get(10), Some(ParamValue::U8(0))); // m0_mode
        assert_eq!(r.param_get(14), Some(ParamValue::U16(500)));
        assert_eq!(r.param_get(15), Some(ParamValue::Bool(true)));
        assert_eq!(r.param_get(16), None);

        assert!(r.param_set_f32(6, 99.0));
        assert_eq!(r.mat[1][0], 99.0);
        assert!(r.param_set_f32(10, 1.0));
        assert_eq!(r.motors[0].mode, Mode::B);
        assert!(r.param_set_f32(14, 70000.0)); // saturates
        assert_eq!(r.iters, u16::MAX as usize);
        assert!(r.param_set_f32(15, 0.2));
        assert!(!r.enabled);
        assert!(!r.param_set_f32(16, 0.0));
    }
}
